name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: check license
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - name: license-check-action with valid
      uses: ./
      with:
        allowedLicenses: MIT;BSD-3-Clause
    - name: license-check-action with invalid
      id: license_invalid
      uses: ./
      with:
        allowedLicenses: NONE
      continue-on-error: true
    - name: license-check-action with invalid did not fail
      if: steps.license_invalid.outcome != 'failure'
      run: exit 1
