name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: check license
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - id: licenses_valid
      uses: ./
      with:
        licenseWhitelist: MIT;BSD-3-Clause
    - id: licenses_invalid
      uses: ./
      with:
        licenseWhitelist: NONE
      continue-on-error: true
    - name: licenses_invalid check failed
      if: steps.licenses_invalid.outcome != 'failure'
      run: exit 1
