name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: check license
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3
    - id: check_success
      uses: ./
      with:
        licenseWhitelist: MIT;BSD-3-Clause
    - id: check_fail
      uses: ./
      with:
        licenseWhitelist: NONE
      continue-on-error: true
